import { Map, Marker } from 'pigeon-maps'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Header from './compo/Header';

export default function Contact() {
    return (<>
        <Head>
        <title>Store | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
        <div className={styles.container}>
            <div className={styles.maps}>
                <Map  defaultCenter={[15.8804229,108.3331808]} defaultZoom={15} boxClassname={styles.maps} warningZIndex={-1}>
                    <Marker 
                        width={20}
                        anchor={[15.8804229,108.3331808]} 
                        color={"#ccc"} 
                    />
                </Map>
            </div>
            <div className={styles.contact}>
                <h1>Contact</h1>
                <label className={styles.label}>City</label><br/>
                <label className={styles.info}>Hoi An</label><br/>
                <label className={styles.label}>Khoa</label><br/>
                <label className={styles.info}>139 Ly Thuong Kiet, Son Phong </label><br/>
                <label className={styles.label}>Phone</label><br/>
                <label className={styles.info}>+0121 966232</label><br/>
                <label className={styles.label}>Email</label><br/>
                <label className={styles.info}>anymous@gmail.com</label><br/>
            </div>
        </div>
        </>
    )
}//34.9206089,-1.3259371,18z